config/routes.rb
Rails.application.routes.draw do
devise_for :users
resources :posts do 
  resources :likes
root 'posts#index'
end 

resources :tags

end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_attached_file :picture, 
    styles: { medium: '400x400>' }, 
    storage: :s3,
    s3_credentials: {
      bucket: 'Inster_Makers',
      access_key_id: Rails.application.secrets.s3_access_key,
      secret_access_key: Rails.application.secrets.s3_secret_key
    }

  validates_attachment_content_type :picture, :content_type => /\Aimage\/.*\Z/
  belongs_to :user
  has_and_belongs_to_many :tags
  has_many :likes

  def tag_names
    ''
  end

  def tag_names=(tag_names)
    return if tag_names.blank?

    tag_names.split(/,\s?/).uniq.each do |tag_name|
      puts tag_name
      formatted_name = '#' + tag_name.delete('#')

      tag = Tag.find_or_create_by(name: formatted_name)
      self.tags << tag
    # tags.create(name: )
    end
  end

end

app/models/tag.rb
class Tag < ActiveRecord::Base
    has_and_belongs_to_many :posts
    validates :name, uniqueness: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def new
    WebsocketRails[:likes].trigger 'hi', {}

    redirect_to '/posts'
  end

  def create 
    @post = Post.find params[:post_id]
    @post.likes.create
    WebsocketRails[:likes].trigger 'new', { id: @post.id, new_like_count: @post.likes.count}




    redirect_to '/posts'
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def index
    @posts = Post.all
  end

  def new 
    @post = Post.new
  end

  def create
    
    @post = Post.new(params[:post].permit(:title, :description, :picture, :tag_names))
    @post.user = current_user
    @post.save!

    redirect_to posts_path
  end

    def destroy
      @post = current_user.posts.find params[:id]
      @post.destroy
      
      flash[:notice] = 'Successfully deleted'
    rescue ActiveRecord::RecordNotFound
      flash[:alert] = 'This is not your post!'
    ensure
      redirect_to '/posts'
    end


  # def login_as_user
  # end

#     def edit
#       @post = Post.find(params[:id])

#       if @post.update(params["post"].permit(:title, :description))
#         redirect_to '/posts'
#       else
#         render 'edit'
#   end
# end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Instamaker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if user_signed_in? %>
  <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
  <%= link_to('Edit registration', edit_user_registration_path) %>
<% else %>
  <%= link_to('Login', new_user_session_path)  %>  
  <%= link_to('Register', new_user_registration_path)  %>
<% end %>

<% if notice %>
  <p class="notice"><%= notice %></p>
<% end %>

<% if alert %>
  <p class="alert"><%= alert %></p>
<% end %>


<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">MakersInk</a>
    </div>
    <div class="navbar-collapse collapse">
      <form class="navbar-form navbar-right" role="form">
        <div class="form-group">
          <input type="text" placeholder="Email" class="form-control">
        </div>
            <div class="form-group">
          <input type="password" placeholder="Password" class="form-control">
        </div>
        <button type="submit" class="btn btn-success">Sign in</button>
      </form>
    </div><!--/.navbar-collapse -->
  </div>
</div>

<%= yield %>


<div class="container">
  <footer>
    <p>&copy; Makersink 2014</p>
  </footer>
</div> <!-- /container -->

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title, required: true %>

  <%= f.label :description %>
  <%= f.text_field :description, required: true %>

  <%= f.submit %>
<% end %>

app/views/posts/_post.html.erb
_post.html.erb

app/views/posts/edit.html.erb
edit.html.erb

app/views/posts/index.html.erb
<div class="jumbotron">
  <div class="container top">
    <h1>Hello, world!</h1>
    <p>
Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, </p>
    <p>
      <%= link_to 'Sign Up', new_user_registration_path, class: 'btn btn-primary btn-lg' %>
    </p>
  </div>
</div>

<div class='container'>
  <% if @posts.none? %>
    No posts yet
  <% else %>
    <div class='row'>
      <% @posts.each do |post| %>
        <div class='col-sm-4 post' data-id='<%= post.id %>'>

            <div class="panel panel-default">
              <div class="panel-heading">
                <h3 class="panel-title"><%= post.title %></h3>
              </div>
              <div class="panel-body">
                <%= image_tag post.picture.url(:medium), class: 'uploaded-pic' %>
                <p>
                  <% post.tags.each do |tag| %>
                    <%= link_to tag.name, '#' %>
                  <% end %>
                </p>
                <div class='buttons'>
                  <% if post.user == current_user %>
                    <%= link_to 'Delete', post_path(post), method: :delete,
                      class: 'btn btn-lg btn-danger' %>   
                  <% end %>
                   <%= link_to 'Show More', '#', class: 'btn btn-lg btn-info', data: { toggle: 'modal', target: ".image-modal-#{post.id}" } %>

                   <%= link_to "♡ #{post.likes.count}", post_likes_path(post), method: :post, class: 'btn btn-lg btn-default like-btn' %>
                </div>
              </div>
            </div>
          </div>

          <div class="modal fade image-modal-<%= post.id %>">
            <div class="modal-dialog modal-lg">
              <div class="modal-content">
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times:</button>
                  <h4 class="modal-title"><%= post.title %></h4>
                </div>

                <div class='modal-body'>
                <%= image_tag post.picture.url %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>

    <%= link_to "Make a Post", new_post_path %>
    <%= link_to "New post" %>

app/views/posts/new.html.erb
<%= form_for @post, html: { multipart: true } do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :description %>
  <%= f.text_area :description %>

  <%= f.label :picture %>
  <%= f.file_field :picture %>

  <%= f.label :tag_names, 'Tags' %>
  <%= f.text_field :tag_names, data: { role: 'tagsinput' } %>

  <%= f.submit 'Create Post' %>
<% end %>